"""Add live notification channel table

Revision ID: 1134d0b4c803
Revises: 61fd0edcab58
Create Date: 2025-12-30 19:48:16.490889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1134d0b4c803"
down_revision: str | Sequence[str] | None = "61fd0edcab58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "livenotificationchannel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("broadcaster", sa.String(), nullable=False),
        sa.Column("text_template", sa.String(), nullable=False),
        sa.Column("target_channel", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_livenotificationchannel")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("livenotificationchannel")
    # ### end Alembic commands ###
