"""Remove broadcaster name from LiveNotificationChannel table

Revision ID: 174a7805e616
Revises: 9701b4272c26
Create Date: 2026-01-04 15:21:04.235330

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "174a7805e616"
down_revision: str | Sequence[str] | None = "9701b4272c26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("livenotificationchannel", "broadcaster_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("livenotificationchannel", sa.Column("broadcaster_name", sa.VARCHAR(), nullable=False, default=""))
    # ### end Alembic commands ###
