"""Update tables to use correct DateTime type

Revision ID: 1e250ee04152
Revises: 4ca9a33d065f
Create Date: 2026-01-11 19:58:22.581868

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1e250ee04152"
down_revision: str | Sequence[str] | None = "4ca9a33d065f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
