"""Add table for entrance sounds

Revision ID: 4209530666cd
Revises: 8563357d6e5d
Create Date: 2026-01-03 11:28:32.326838

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4209530666cd"
down_revision: str | Sequence[str] | None = "8563357d6e5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entrancesound",
        sa.Column("twitch_user_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("twitch_user_id", name=op.f("pk_entrancesound")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entrancesound")
    # ### end Alembic commands ###
