"""add volume to soundboard clips

Revision ID: 5f9af2cc10f5
Revises: a9e93c8c6f82
Create Date: 2026-02-14 14:43:56.946450

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f9af2cc10f5"
down_revision: str | Sequence[str] | None = "a9e93c8c6f82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("soundboardcommand", sa.Column("volume", sa.Float(), server_default=sa.text("(1.0)"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("soundboardcommand", "volume")
    # ### end Alembic commands ###
