"""Store both broadcaster name and ID

Revision ID: 8fac49eb043c
Revises: 1134d0b4c803
Create Date: 2025-12-31 10:26:01.953378

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fac49eb043c"
down_revision: str | Sequence[str] | None = "1134d0b4c803"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("livenotificationchannel", sa.Column("broadcaster_name", sa.String(), nullable=False))
    op.add_column("livenotificationchannel", sa.Column("broadcaster_id", sa.String(), nullable=False))
    op.drop_column("livenotificationchannel", "broadcaster")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("livenotificationchannel", sa.Column("broadcaster", sa.VARCHAR(), nullable=False))
    op.drop_column("livenotificationchannel", "broadcaster_id")
    op.drop_column("livenotificationchannel", "broadcaster_name")
    # ### end Alembic commands ###
