"""Revert datetime type in tables

Revision ID: 902cb24ac436
Revises: 1e250ee04152
Create Date: 2026-01-11 20:04:53.310798

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "902cb24ac436"
down_revision: str | Sequence[str] | None = "1e250ee04152"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
