"""Create table for raid event actions

Revision ID: a9e93c8c6f82
Revises: 902cb24ac436
Create Date: 2026-01-17 15:00:19.662555

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9e93c8c6f82"
down_revision: str | Sequence[str] | None = "902cb24ac436"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raideventaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("twitch_user_id", sa.String(), nullable=True),
        sa.Column("chat_message_to_send", sa.String(), nullable=True),
        sa.Column("soundboard_clip_to_play", sa.String(), nullable=True),
        sa.Column("should_shoutout", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["soundboard_clip_to_play"],
            ["soundboardcommand.name"],
            name=op.f("fk_raideventaction_soundboard_clip_to_play_soundboardcommand"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raideventaction")),
        sa.UniqueConstraint("twitch_user_id", name=op.f("uq_raideventaction_twitch_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raideventaction")
    # ### end Alembic commands ###
