"""Add table for pending soundboard clips

Revision ID: bfd170595873
Revises: 153518e030e6
Create Date: 2026-01-02 12:08:23.228696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfd170595873"
down_revision: str | Sequence[str] | None = "153518e030e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pendingsoundboardclip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("uploader_twitch_id", sa.String(), nullable=False),
        sa.Column("uploader_twitch_login", sa.String(), nullable=False),
        sa.Column("uploader_twitch_display_name", sa.String(), nullable=False),
        sa.Column("may_persist_uploader_info", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pendingsoundboardclip")),
    )
    op.add_column("soundboardcommand", sa.Column("uploader_twitch_id", sa.String(), nullable=True))
    op.add_column("soundboardcommand", sa.Column("uploader_twitch_login", sa.String(), nullable=True))
    op.add_column("soundboardcommand", sa.Column("uploader_twitch_display_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("soundboardcommand", "uploader_twitch_display_name")
    op.drop_column("soundboardcommand", "uploader_twitch_login")
    op.drop_column("soundboardcommand", "uploader_twitch_id")
    op.drop_table("pendingsoundboardclip")
    # ### end Alembic commands ###
