"""add script and scriptstore tables

Revision ID: c96656cce2d6
Revises: 90615bd027fd
Create Date: 2025-11-09 17:53:20.065842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c96656cce2d6"
down_revision: str | Sequence[str] | None = "90615bd027fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "script",
        sa.Column("command", sa.String(), nullable=False),
        sa.Column("source_code", sa.String(), nullable=False),
        sa.Column("script_json", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("command", name=op.f("pk_script")),
    )
    op.create_table(
        "scriptstore",
        sa.Column("script_command", sa.String(), nullable=False),
        sa.Column("store_name", sa.String(), nullable=False),
        sa.Column("store_json", sa.String(), nullable=False),
        sa.Column("value_json", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["script_command"],
            ["script.command"],
            name=op.f("fk_scriptstore_script_command_script"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("script_command", "store_name", name=op.f("pk_scriptstore")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scriptstore")
    op.drop_table("script")
    # ### end Alembic commands ###
