"""Add table for received Twitch event messages

Revision ID: cc340445a4ca
Revises: cc79430df495
Create Date: 2026-01-04 12:31:15.504462

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc340445a4ca"
down_revision: str | Sequence[str] | None = "cc79430df495"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receivedtwitchmessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivedtwitchmessage")),
    )
    op.create_index(op.f("ix_receivedtwitchmessage_message_id"), "receivedtwitchmessage", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receivedtwitchmessage_message_id"), table_name="receivedtwitchmessage")
    op.drop_table("receivedtwitchmessage")
    # ### end Alembic commands ###
