"""Add table for automatic shoutouts

Revision ID: d1a4a0aa3ac3
Revises: 51019a3ea980
Create Date: 2026-09-23 13:37:02.847221

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1a4a0aa3ac3"
down_revision: str | Sequence[str] | None = "51019a3ea980"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automaticshoutout",
        sa.Column("twitch_user_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("twitch_user_id", name=op.f("pk_automaticshoutout")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("automaticshoutout")
    # ### end Alembic commands ###
