"""Add table for cached source codes

Revision ID: ef67d17c9d30
Revises: 4209530666cd
Create Date: 2026-01-03 15:24:06.062792

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef67d17c9d30"
down_revision: str | Sequence[str] | None = "4209530666cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cachedsourcecode",
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source_code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("url", name=op.f("pk_cachedsourcecode")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cachedsourcecode")
    # ### end Alembic commands ###
