"""Add tables for user profiles and email verification tokens

Revision ID: f1c0742a11df
Revises: 174a7805e616
Create Date: 2026-01-11 18:29:21.473074

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1c0742a11df"
down_revision: str | Sequence[str] | None = "174a7805e616"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emailverificationtoken",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("twitch_user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_emailverificationtoken")),
    )
    op.create_table(
        "userprofile",
        sa.Column("twitch_user_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("email_is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("twitch_user_id", name=op.f("pk_userprofile")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userprofile")
    op.drop_table("emailverificationtoken")
    # ### end Alembic commands ###
